=== cernopendata/cernopendata-portal/cernopendata/jsonschemas/records/docs-v1.0.0.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "description": "Describe information needed for article entity.",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "_conceptrecid": {
      "type": "string"
    },
    "_id_field": {
      "type": "string"
    },
    "_versions": {
      "additionalProperties": false,
      "properties": {
        "index": {
          "type": "integer"
        },
        "is_latest": {
          "type": "boolean"
        },
        "latest_index": {
          "type": "integer"
        }
      },
      "type": "object"
    },
    "author": {
      "type": "string"
    },
    "body": {
      "additionalProperties": false,
      "properties": {
        "content": {
          "type": "string"
        },
        "format": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "date_created": {
      "items": {
        "description": "The data-taking year for which the documentation was produced",
        "type": "string"
      },
      "type": "array"
    },
    "date_published": {
      "description": "The year of publication on the portal",
      "type": "string"
    },
    "experiment": {
      "items": {
        "description": "The name of the experiment the author is part of",
        "type": "string"
      },
      "type": "array"
    },
    "featured": {
      "type": "integer"
    },
    "id": {
      "title": "id",
      "type": "string"
    },
    "related": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "prerelease": {
      "type": "string"
    },
    "screenshot": {
      "type": "string"
    },
    "slug": {
      "type": "string"
    },
    "short_description": {
      "additionalProperties": false,
      "properties": {
        "content": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "stripping": {
      "additionalProperties": false,
      "properties": {
        "stream": {
          "description": "Stripping stream information, used notably by LHCb",
          "type": "string"
        },
        "version": {
          "description": "Stripping version information, used notably by LHCb",
          "type": "string"
        }
      },
      "type": "object"
    },
    "tags": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "title": {
      "title": "Title",
      "type": "string"
    },
    "type": {
      "additionalProperties": false,
      "properties": {
        "primary": {
          "type": "string"
        },
        "secondary": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    }
  },
  "title": "Article Schema.",
  "type": "object"
}

=== cernopendata/cernopendata-portal/cernopendata/modules/fixtures/data/docs/cod-about/cod-about.json
[
  {
    "body": {
      "content": "cod-about.md",
      "format": "md"
    },
    "short_description": {
      "content": "The CERN Open Data portal is the access point to a growing range of data produced through the research performed at CERN. It disseminates the preserved output from various research activities, including accompanying software and documentation which is needed to understand and analyse the data being shared."
    },
    "slug": "about",
    "tags": ["Getting Started"],
    "title": "CERN Open Data Portal",
    "type": {
      "primary": "Documentation",
      "secondary": ["About"]
    }
  }
]

=== cernopendata/cernopendata-portal/cernopendata/modules/fixtures/data/docs/cod-colddata/cod-colddata.json
[
  {
    "author": "CERN Open Data team",
    "body": {
      "content": "cod-colddata.md",
      "format": "md"
    },
    "date_published": "2025-10-07",
    "featured": 1,
    "short_description": {
      "content": "The increasing amount of data hosted in the portal calls for storing the data in a more cost-effective way."
    },
    "slug": "colddata",
    "title": "Introducing cold storage in the CERN Open Data portal",
    "type": {
      "primary": "News"
    }
  }
]

=== cernopendata/cernopendata-portal/cernopendata/modules/fixtures/data/docs/cod-terms-of-use/cod-terms-of-use.json
[
  {
    "body": {
      "content": "cod-terms-of-use.md",
      "format": "md"
    },
    "short_description": {
      "content": "The CERN Open Data Portal is offered by CERN as part of its mission to publish the results of its experimental and theoretical work."
    },
    "slug": "terms-of-use",
    "title": "CERN Open Data Terms of Use",
    "type": {
      "primary": "Documentation",
      "secondary": ["About"]
    }
  }
]

=== cernopendata/cernopendata-portal/cernopendata/modules/fixtures/data/docs/simulated-dataset-categories/simulated-dataset-categories.json
[
  {
    "body": {
      "content": "simulated-dataset-categories.md",
      "format": "md"
    },
    "short_description": {
      "content": "Description of the simulated dataset categories used in the CERN Open Data Portal."
    },
    "slug": "simulated-dataset-categories",
    "tags": ["Getting Started"],
    "title": "Simulated Dataset Categories",
    "type": {
      "primary": "Documentation",
      "secondary": ["Guide"]
    }
  }
]

=== cernopendata/cernopendata-portal/cernopendata/modules/fixtures/data/docs/cern-open-data-policy-for-lhc-experiments/cern-open-data-policy-for-lhc-experiments.json
[
  {
    "author": "CERN",
    "body": {
      "content": "cern-open-data-policy-for-lhc-experiments.md",
      "format": "md"
    },
    "date_published": "2020-12-11",
    "experiment": ["ALICE", "ATLAS", "CMS", "LHCb"],
    "short_description": {
      "content": "CERN Open Data Policy for the LHC Experiments"
    },
    "slug": "cern-open-data-policy-for-lhc-experiments",
    "title": "CERN Open Data Policy for the LHC Experiments",
    "type": {
      "primary": "News"
    }
  }
]

=== cernopendata/cernopendata-portal/cernopendata/modules/fixtures/data/docs/cod-privacy-policy/cod-privacy-policy.json
[
  {
    "body": {
      "content": "cod-privacy-policy.md",
      "format": "md"
    },
    "short_description": {
      "content": "CERN does not track, collect or retain personal information from users of CERN Open Data Portal, except as otherwise provided herein. In order to enhance CERN Open Data Portal and monitor traffic, information..."
    },
    "slug": "privacy-policy",
    "title": "CERN Open Data Privacy Policy",
    "type": {
      "primary": "Documentation",
      "secondary": [
        "Policy"
      ]
    }
  }
]
